//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class news
    {
        public long ID { get; set; }
        public long CATEGORY_ID { get; set; }
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public string DETAIL { get; set; }
        public string IMAGE { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public long USER_ID { get; set; }
    }
}
